//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanLangDoctor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BENH_NHAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BENH_NHAN()
        {
            this.DON_THUOC = new HashSet<DON_THUOC>();
        }
    
        public int ID_BENHNHAN { get; set; }
        public string TEN_BN { get; set; }
        public string GIOI_TINH { get; set; }
        public System.DateTime NGAY_SINH { get; set; }
        public string EMAIL { get; set; }
        public string SDT { get; set; }
        public string CHUAN_DOAN { get; set; }
        public Nullable<int> ID_BACSI { get; set; }
        public Nullable<int> ID_BENH_AN { get; set; }
    
        public virtual BACSI BACSI { get; set; }
        public virtual BENH_AN BENH_AN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DON_THUOC> DON_THUOC { get; set; }
    }
}
