//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanLangDoctor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BENH_AN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BENH_AN()
        {
            this.BENH_NHAN = new HashSet<BENH_NHAN>();
        }
    
        public int ID_BENHAN { get; set; }
        public string KET_QUA { get; set; }
        public string CHUAN_DOAN { get; set; }
        public string TIEN_SU_BENH { get; set; }
        public string GHI_CHU { get; set; }
        public Nullable<int> ID_BENH_NHAN { get; set; }
        public Nullable<int> ID_KHOA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BENH_NHAN> BENH_NHAN { get; set; }
        public virtual BENH_NHAN BENH_NHAN1 { get; set; }
        public virtual KHOA KHOA { get; set; }
    }
}
