//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanLangDoctor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BENH_AN
    {
        public int ID_BENH_AN { get; set; }
        public string KET_QUA { get; set; }
        public string CHUAN_DOAN { get; set; }
        public string TIEN_SU_BENH { get; set; }
        public string GHI_CHU { get; set; }
        public Nullable<int> ID_DON_THUOC { get; set; }
        public int ID_BENH_NHAN { get; set; }
    
        public virtual DON_THUOC DON_THUOC { get; set; }
        public virtual BENH_NHAN BENH_NHAN { get; set; }
    }
}
