//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanLangDoctor.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class BENH_NHAN
    {
        public int ID_BENH_NHAN { get; set; }
        public string TEN_BN { get; set; }
        public string GIOI_TINH { get; set; }
        public Nullable<System.DateTime> NGAY_SINH { get; set; }
        [Required(ErrorMessage = "Hãy nhập số điện thoại."),
            StringLength(maximumLength: 10, ErrorMessage = "Số điện thoại tối đa là 10 số."),
            MinLength(10, ErrorMessage = "Số điện thoại có ít nhất là 10 số."),
            RegularExpression("^[0-9_]*$", ErrorMessage = "Dữ liệu nhập vào phải có dạng số (0-9)")]
        public string SDT { get; set; }
        public string DIA_CHI { get; set; }
        public string ID_EMAIL { get; set; }
        public Nullable<int> ID_BENH_AN { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual BENH_AN BENH_AN { get; set; }
        public virtual BENH_AN BENH_AN1 { get; set; }
    }
}
