//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanLangDoctor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANH_GIA
    {
        public int ID { get; set; }
        public int ID_BACSI { get; set; }
        public int RATING { get; set; }
        public string NHAN_XET { get; set; }
        public string ID_USER { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual BACSI BACSI { get; set; }
    }
}
