//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanLangDoctor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAT_LICH_TU_VAN
    {
        public int ID { get; set; }
        public string ID_USER { get; set; }
        public System.DateTime NGAY_KHAM { get; set; }
        public int ID_BAC_SI { get; set; }
        public string LINK_GG { get; set; }
        public int TRANG_THAI { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual BACSI BACSI { get; set; }
    }
}
