//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanLangDoctor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DON_THUOC
    {
        public int ID_DON_THUOC { get; set; }
        public string CHUAN_DOAN { get; set; }
        public string CHI_DINH { get; set; }
        public string LOI_DAN { get; set; }
        public System.DateTime NGAY_LAP { get; set; }
        public Nullable<int> ID_BENH_NHAN { get; set; }
        public Nullable<int> ID_BACSI { get; set; }
    
        public virtual BACSI BACSI { get; set; }
        public virtual BENH_NHAN BENH_NHAN { get; set; }
    }
}
