//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanLangDoctor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DON_THUOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DON_THUOC()
        {
            this.THUOCs = new HashSet<THUOC>();
        }
    
        public int ID_DON_THUOC { get; set; }
        public string KET_QUA { get; set; }
        public string CHUAN_DOAN { get; set; }
        public string CHI_DINH { get; set; }
        public string LOI_DAN { get; set; }
        public Nullable<System.DateTime> NGAY_LAP { get; set; }
        public int ID_BACSI { get; set; }
        public int ID_SO_KHAM_BENH { get; set; }
    
        public virtual BACSI BACSI { get; set; }
        public virtual SO_KHAM_BENH SO_KHAM_BENH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THUOC> THUOCs { get; set; }
        public Nullable<int> ID_THUOC { get; set; }
        public virtual THUOC THUOC { get; set; }
    }
}
