//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanLangDoctor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEEDBACK
    {
        public int ID_FEEDBACK { get; set; }
        public string TEN_NDG { get; set; }
        public string SDT { get; set; }
        public string GOP_Y { get; set; }
        public string DANH_GIA { get; set; }
        public string ID_USER { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
