//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanLangDoctor.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class FEEDBACK
    {
        public int ID_FEEDBACK { get; set; }
        [Required(ErrorMessage = "Hãy nhập tên")]
        public string TEN_NDG { get; set; }
        [Required(ErrorMessage = "Hãy nhập số điện thoại."),
            StringLength(maximumLength: 10, ErrorMessage = "Số điện thoại tối đa là 10 số."),
            MinLength(10, ErrorMessage = "Số điện thoại có ít nhất là 10 số."),
            RegularExpression("^[0-9_]*$", ErrorMessage = "Dữ liệu nhập vào phải có dạng số (0-9)")]
        public string SDT { get; set; }
        public string GOP_Y { get; set; }
        public string DANH_GIA { get; set; }
        public string ID_USER { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
