//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanLangDoctor.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CP24Team02Entities : DbContext
    {
        public CP24Team02Entities()
            : base("name=CP24Team02Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<BACSI> BACSIs { get; set; }
        public virtual DbSet<BENH_NHAN> BENH_NHAN { get; set; }
        public virtual DbSet<CHI_TIET_DON_THUOC> CHI_TIET_DON_THUOC { get; set; }
        public virtual DbSet<DANG_KY> DANG_KY { get; set; }
        public virtual DbSet<DANH_GIA> DANH_GIA { get; set; }
        public virtual DbSet<DANH_MUC_THUOC> DANH_MUC_THUOC { get; set; }
        public virtual DbSet<DANH_MUC_TIN> DANH_MUC_TIN { get; set; }
        public virtual DbSet<DAT_LICH> DAT_LICH { get; set; }
        public virtual DbSet<DAT_LICH_TU_VAN> DAT_LICH_TU_VAN { get; set; }
        public virtual DbSet<DON_THUOC> DON_THUOC { get; set; }
        public virtual DbSet<FEEDBACK> FEEDBACKs { get; set; }
        public virtual DbSet<KHOA> KHOAs { get; set; }
        public virtual DbSet<NHA_SAN_XUAT> NHA_SAN_XUAT { get; set; }
        public virtual DbSet<SO_KHAM_BENH> SO_KHAM_BENH { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<THUOC> THUOCs { get; set; }
        public virtual DbSet<TIN_TUC> TIN_TUC { get; set; }
    }
}
